apache/incubator-kie-benchmarks

- jbpm-benchmarks/jbpm-performance-tests/pom.xml
Hi, @baldimir,
I have added a warmUpTime property to jbpm tests.
Thanks,
Marian
> Add warmUpTime property

- drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/runtime/DMNEvaluatePojoInputBenchmark.java
- drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/runtime/model/Person.java
- drools-benchmarks/src/main/resources/dmn/pojo-input.dmn
@tarilabs is this all right for the accessor cache measurement?
> Add DMN benchmark that measures evaluating decision with pojo input

- jbpm-benchmarks/jbpm-performance-tests/pom.xml
- jbpm-benchmarks/jbpm-performance-tests/src/main/filtered-resources/META-INF/persistence.xml
- jbpm-benchmarks/jbpm-performance-tests/src/main/filtered-resources/datasource.properties
- jbpm-benchmarks/jbpm-performance-tests/src/main/java/org/jbpm/test/performance/jbpm/JBPMController.java
- jbpm-benchmarks/jbpm-performance-tests/src/main/java/org/jbpm/test/performance/jbpm/util/CloseSafeMemoryContextFactory.java
- jbpm-benchmarks/jbpm-performance-tests/src/main/resources/jndi.properties
- jbpm-benchmarks/jbpm-performance-tests/src/main/resources/logback.xml
Guys, impossible has become reality. Narayana in jBPM performance tests and working! Circle is closed.
> Migrate jbpm-performance-tests to Narayana with Tomcat DBCP 2 pooling

- drools-benchmarks/src/main/java/org/drools/benchmarks/turtle/reproducers/DMNEvaluateDecisionNameLengthJITCompilationBenchmark.java
- drools-benchmarks/src/main/resources/dmn/abigone.dmn
- drools-benchmarks/src/main/resources/dmn/abigone_longnames.dmn
/cc @baldimir please review? I used this variant for JITting otherwise it would take >10m per benchmark run to JIT making the JMH timeout. Additionally, I have added a `main()` entry point of utility for Profiling sessions on this variant.
> Provide DMN "long name" Turtle benchmark variant for JITting checks

- optaplanner-benchmarks/optaplanner-perf-benchmark/src/main/java/org/jboss/qa/brms/performance/realworld/nurserostering/NurseRosteringBenchmark.java
Depends on merging of [this PR](https://github.com/kiegroup/kie-benchmarks/pull/38).
> PLANNER-1380: Add Nurse Rostering benchmark

- optaplanner-benchmarks/optaplanner-perf-framework/src/main/java/org/jboss/qa/brms/performance/examples/conferencescheduling/persistence/ConferenceSchedulingGenerator.java
Lab talk count is initialized with value derived from given parameters.
> Fix generator throwing exception

- drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/runtime/DMNEvaluateDecisionTablesSparseBenchmark.java
> DMNEvaluateDecisionTablesSparseBenchmark variations parameters

- update-version.sh
A back-port to 7.26.x will follow once this PR is approved.
> Create a script for updating a version of the project

- jbpm-benchmarks/kieserver-assets/src/main/resources/processes/testContinuousTaskAssignment.bpmn
- jbpm-benchmarks/kieserver-performance-tests/src/main/java/org/jbpm/test/performance/taskassigning/TaskAssigning.java
- jbpm-benchmarks/kieserver-performance-tests/src/main/java/org/jbpm/test/performance/taskassigning/batch/TaskAssigningBatch.java
- jbpm-benchmarks/kieserver-performance-tests/src/main/java/org/jbpm/test/performance/taskassigning/updates/TaskAssigningUpdates.java
- jbpm-benchmarks/kieserver-performance-tests/src/main/java/org/jbpm/test/performance/taskassigning/updates/TaskAssigningUpdates_1800.java
- jbpm-benchmarks/kieserver-performance-tests/src/main/java/org/jbpm/test/performance/taskassigning/updates/TaskAssigningUpdates_3600.java
- jbpm-benchmarks/kieserver-performance-tests/src/main/resources/logback.xml
- jbpm-benchmarks/kieserver-performance-tests/src/test/java/org/jbpm/test/performance/taskassigning/TaskStatisticsUtilTest.java
- both scenarios have been stabilized by aborting processes in smaller batches in `before`/`after` methods
- update scenario has been reworked to use a different process definition to induce problem fact changes in the planning extension
> Stabilize task assignment batch scenario and rework the update scenario

- optaplanner-benchmarks/optaplanner-perf-benchmark/src/main/java/org/jboss/qa/brms/performance/realworld/cloudbalancing/CloudBalanceBenchmark.java
- optaplanner-benchmarks/optaplanner-perf-benchmark/src/main/java/org/jboss/qa/brms/performance/realworld/vrp/VehicleRoutingBenchmark.java
- optaplanner-benchmarks/optaplanner-perf-framework/src/main/java/org/jboss/qa/brms/performance/examples/conferencescheduling/ConferenceSchedulingExample.java
- optaplanner-benchmarks/optaplanner-perf-framework/src/main/java/org/jboss/qa/brms/performance/examples/nurserostering/NurseRosteringExample.java
The weekly benchmarks failed due to:
https://github.com/kiegroup/optaplanner/commit/82fb41e096d1d30d969b05213949d3ecf8172c01#diff-db6ddabe91e0367239e1a48db57c1e99
This PR updates references to DRL files from optaplanner-examples.
> Update names of constraints DRL files

- jbpm-benchmarks/kieserver-performance-tests/src/main/java/org/jbpm/test/performance/taskassigning/TaskStatisticsUtil.java
- jbpm-benchmarks/kieserver-performance-tests/src/main/java/org/jbpm/test/performance/taskassigning/updates/TaskAssigningUpdates.java
- jbpm-benchmarks/kieserver-performance-tests/src/test/java/org/jbpm/test/performance/taskassigning/TaskStatisticsUtilTest.java
Locally I can see it speeded up the benchmark run.
> Use a custom query to fetch task events

- jbpm-benchmarks/pom.xml
Merge with: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1350
> Manage postgresql version with kie-parent

- drools-benchmarks/pom.xml
- jbpm-benchmarks/jbpm-performance-tests-jmh/pom.xml
- jbpm-benchmarks/jbpm-performance-tests/pom.xml
- jbpm-benchmarks/kieserver-assets/pom.xml
- jbpm-benchmarks/kieserver-performance-tests/pom.xml
- jbpm-benchmarks/pom.xml
- optaplanner-benchmarks/optaplanner-perf-benchmark/pom.xml
- optaplanner-benchmarks/optaplanner-perf-framework/pom.xml
- optaplanner-benchmarks/pom.xml
- pom.xml
when doing a mvn clean install -DskipTests after upgrading to see if everything builds I get:
https://gist.github.com/mbiarnes/97bbaa6f1ca9b225c05d6fc60c5547da.
Can you fix this please?
> upgraded to next SNAPSHOT

- drools-benchmarks/src/main/java/org/drools/benchmarks/operators/AlphaNodeRangeIndexingBenchmark.java
https://issues.redhat.com/browse/DROOLS-5759
> [DROOLS-5759] Add benchmark for alpha node range index

- jbpm-benchmarks/jbpm-performance-tests-jmh/src/main/java/org/jbpm/test/performance/jbpm/JBPMController.java
- jbpm-benchmarks/jbpm-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LHumanTaskProcess.java
- jbpm-benchmarks/jbpm-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LParallelGatewayTwoTimesProcess.java
BAQE-1595 - Change teardown and setup to run every iteration of jBPMJMH tests
> BAQE-1595 - Change teardown and setup to run every iteration of jBPMJMH tests

- drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/decisiontable/DMNDTChineseYearBenchmark.java
- drools-benchmarks/src/main/resources/dmn/ChineseLunarYears.dmn
ref https://issues.redhat.com/browse/DROOLS-6023
> DROOLS-6023 DMN inline memoization of FEEL temporal literal constants

- drools-benchmarks/pom.xml
- drools-benchmarks/src/main/java/org/drools/benchmarks/pmml/runtime/PMMLEvaluateRandomForestBenchmark.java
- drools-benchmarks/src/main/java/org/drools/benchmarks/pmml/runtime/clustering/PMMLEvaluateSingleIrisKMeansClusteringBenchmark.java
- drools-benchmarks/src/main/java/org/drools/benchmarks/pmml/runtime/mining/PMMLEvaluateRandomForestBenchmark.java
- drools-benchmarks/src/main/java/org/drools/benchmarks/pmml/runtime/regression/PMMLEvaluateLinearRegressionSampleWithTransformationsBenchmark.java
- drools-benchmarks/src/main/java/org/drools/benchmarks/pmml/runtime/scorecard/PMMLEvaluateSimpleScorecardWithTransformationsBenchmark.java
- drools-benchmarks/src/main/java/org/drools/benchmarks/pmml/runtime/tree/PMMLEvaluateSampleMineTreeModelWithTransformationsBenchmark.java
- drools-benchmarks/src/main/java/org/drools/benchmarks/pmml/util/PMMLUtil.java
- drools-benchmarks/src/main/resources/pmml/LinearRegressionSampleWithTransformations.pmml
- drools-benchmarks/src/main/resources/pmml/SampleMineTreeModelWithTransformations.pmml
- drools-benchmarks/src/main/resources/pmml/SimpleScorecardWithTransformations.pmml
- drools-benchmarks/src/main/resources/pmml/SingleIrisKMeansClustering.pmml
@danielezonca @mariofusco @jiripetrlik
See https://issues.redhat.com/browse/BAPL-2029
Could you please verify settings/annotations correctness ? Thanks!
> [BAPL-2029] First level benchmarks for trusty pmml

- .github/workflows/pull_request.yml
Enable GH action for main changes
> Change GitHub action to run pull request changes on main

- optaplanner-8-benchmarks/pom.xml
Add a plugin to update dependencies with maven command
> Add version plugin to update OptaPlanner dependency

- .github/workflows/pull_request_8.x.yml
- optaplanner-8-benchmarks/README.md
- pom.xml
Change PR check to fit the new branch request
> Add PR check for OptaPlanner 8.x

- optaplanner-7-benchmarks/optaplanner-perf-benchmark/pom.xml
- optaplanner-7-benchmarks/optaplanner-perf-benchmark/src/main/java/org/jboss/qa/brms/performance/localsearch/nurserostering/moveselector/AbstractNurseRosteringMoveSelectorBenchmark.java
- optaplanner-7-benchmarks/optaplanner-perf-framework/src/main/java/org/jboss/qa/brms/performance/examples/nurserostering/NurseRosteringExample.java
- optaplanner-7-benchmarks/optaplanner-perf-framework/src/main/resources/org/jboss/qa/brms/performance/examples/nurserostering/solver/nurseRosteringSolverConfig.xml
After https://github.com/kiegroup/droolsjbpm-knowledge/commit/2080e9ced8c3972b8b1c08c8b6e6500a2282985e  
it became impossible to pass URL of kie.conf. Excluded it.
Changed drl path for nurse rostering
> Fix Nurse Rostering test

- drools-benchmarks/src/main/java/org/drools/benchmarks/turtle/buildtime/BuildKJarFromResourceStoreFirstBenchmark.java
- drools-benchmarks/src/main/java/org/drools/benchmarks/turtle/buildtime/BuildKieBaseFromContainerStoreFirstBenchmark.java
- Benchmark
Retrospectively added benchmarks for https://issues.redhat.com/browse/DROOLS-6053
> [DROOLS-6053] Reduce unnecessary classloading by parent classloader

- drools-benchmarks/pom.xml
@danielezonca 
Forward of https://github.com/kiegroup/kie-benchmarks/pull/141
> [7.x][RHPAM-3979] Fixing benchmark jar creation 

- optaplanner-8-benchmarks/optaplanner-perf-benchmark/pom.xml
Avoid an exception while running perf tests on jdk17 https://openjdk.java.net/jeps/403
> Omit reflective access exception

- optaplanner-8-benchmarks/optaplanner-perf-framework/data/nurserostering/long01.xml
- optaplanner-8-benchmarks/optaplanner-perf-framework/data/nurserostering/medium01.xml
Contrary to https://github.com/kiegroup/kie-benchmarks/pull/149 change only empty list
> Improve datafiles to avoid xstream.converters.ConversionException

- optaplanner-8-benchmarks/optaplanner-perf-framework/src/main/java/org/jboss/qa/brms/performance/examples/tsp/TravelingSalesmanExample.java
- optaplanner-8-benchmarks/pom.xml
In the newer 8.12 version of OptaPlanner this example has been moved to another package
> Traveling salesmen example package change

- jbpm-benchmarks/jbpm-performance-tests-jmh/pom.xml
- jbpm-benchmarks/jbpm-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/L1000HumanTasksComplete.java
- jbpm-benchmarks/jbpm-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/L1000HumanTasksQueryPagination.java
- jbpm-benchmarks/jbpm-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/L1000HumanTasksStart.java
- jbpm-benchmarks/jbpm-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/L1000ProcessesSignal.java
- jbpm-benchmarks/jbpm-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LGroupHumanTaskProcess.java
- jbpm-benchmarks/jbpm-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LHumanTaskProcess.java
- jbpm-benchmarks/jbpm-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LHumanTaskProcessWithListeners.java
- jbpm-benchmarks/jbpm-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LIntermediateSignalProcess.java
- jbpm-benchmarks/jbpm-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LParallelGatewayProcess.java
- jbpm-benchmarks/jbpm-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LParallelGatewayTenTimesProcess.java
- jbpm-benchmarks/jbpm-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LParallelGatewayTwoTimesProcess.java
- jbpm-benchmarks/jbpm-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LRuleTaskProcess.java
- jbpm-benchmarks/jbpm-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LScriptTaskProcess.java
- jbpm-benchmarks/jbpm-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LStartEndProcess.java
- jbpm-benchmarks/kieserver-performance-tests-jmh/pom.xml
- jbpm-benchmarks/kieserver-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LServerGroupHumanTaskProcess.java
- jbpm-benchmarks/kieserver-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LServerHumanTaskProcess.java
- jbpm-benchmarks/kieserver-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LServerParallelGatewayTwoTimesProcess.java
- jbpm-benchmarks/kieserver-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LServerRuleTaskProcess.java
- jbpm-benchmarks/kieserver-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LServerStartEndNoCheckProcess.java
- jbpm-benchmarks/kieserver-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LServerStartEndProcess.java
- jbpm-benchmarks/perf-tests-common/pom.xml
- jbpm-benchmarks/perf-tests-common/src/main/java/org/jbpm/test/performance/test/common/AbstractJmhTest.java
- jbpm-benchmarks/perf-tests-common/src/main/java/org/jbpm/test/performance/test/common/PerfdbClean.java
- jbpm-benchmarks/pom.xml
- pom.xml
Cherry-pick of commits regarding  jmh tests and db cleaning.
> BAQE-2134 - Db cleaning in Teardown method of JMH tests

- .ci/jenkins/Jenkinsfile.branch
- .gitignore
**Thank you for submitting this pull request**
**JIRA**: _(please edit the JIRA link if it exists)_ 
[BXMSPROD-1576](https://issues.redhat.com/browse/BXMSPROD-1576)
**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_
* [kie-jenkins-scripts](https://github.com/kiegroup/kie-jenkins-scripts/pull/1195)
* [kie-benchmarks](https://github.com/kiegroup/kie-benchmarks/pull/159)
> BXMSPROD-1576: added Jenkinsfile for creation of new branches

- drools-benchmarks/pom.xml
- optaplanner-benchmarks/optaplanner-perf-benchmark/pom.xml
- optaplanner-benchmarks/optaplanner-perf-framework/pom.xml
- optaplanner-benchmarks/pom.xml
- pom.xml
I think the upgrade happened during the refactoring. Doing it manually now.
> [main] Update version to 8.22.0-SNAPSHOT

- drools-benchmarks/src/main/java/org/drools/benchmarks/session/FirstResponseBenchmark.java
Forward-port PR of https://github.com/kiegroup/kie-benchmarks/pull/179
> [DROOLS-6988] First response time benchmark (#179)

- drools-benchmarks/pom.xml
- optaplanner-benchmarks/optaplanner-perf-benchmark/pom.xml
- optaplanner-benchmarks/optaplanner-perf-framework/pom.xml
- optaplanner-benchmarks/pom.xml
- pom.xml
To avoid confusion with different versions of branches
> Bump kie-benchmarks to 1.0-SNAPSHOT

- drools-benchmarks-parent/drools-benchmarks/src/main/resources/kbase-creation/drl-kbase-creation-1k.drl
- drools-benchmarks-parent/drools-benchmarks/src/main/resources/kbase-creation/drl-kbase-creation-5k.drl
- drools-benchmarks-parent/drools-benchmarks/src/main/resources/kbase-creation/drl-template.drl
- drools-benchmarks-parent/drools-benchmarks/src/main/resources/turtle/fusion-after-before-operators-100.drl
- drools-benchmarks-parent/drools-benchmarks/src/main/resources/turtle/fusion-coincides-during-operators-100.drl
- drools-benchmarks-parent/drools-benchmarks/src/main/resources/turtle/fusion-finishes-finishedby-operators-100.drl
- drools-benchmarks-parent/drools-benchmarks/src/main/resources/turtle/fusion-meets-metby-operators-100.drl
- drools-benchmarks-parent/drools-benchmarks/src/main/resources/turtle/fusion-overlaps-overlappedby-operators-100.drl
- drools-benchmarks-parent/drools-benchmarks/src/main/resources/turtle/fusion-starts-startedby-operators-100.drl
Fixes a couple of wrong paths in resource files - ref kiegroup/kie-issues#59
> [kie-issues#59] Fix package paths for model classes in resource files

- optaplanner-benchmarks/README.md
- optaplanner-benchmarks/optaplanner-perf-benchmark/src/main/java/org/jboss/qa/brms/performance/localsearch/cloudbalance/moveselector/CloudBalancePillarChangeAndSwapMoveSelectorBenchmark.java
- optaplanner-benchmarks/optaplanner-perf-benchmark/src/main/java/org/jboss/qa/brms/performance/localsearch/cloudbalance/moveselector/union/AbstractCloudBalanceMoveSelectorUnionBenchmark.java
- optaplanner-benchmarks/optaplanner-perf-benchmark/src/main/java/org/jboss/qa/brms/performance/localsearch/cloudbalance/moveselector/union/CloudBalancePillarChangeAndSwapMoveSelectorBenchmark.java
- optaplanner-benchmarks/optaplanner-perf-framework/src/main/java/org/jboss/qa/brms/performance/configuration/MoveSelectorConfigurations.java
Created the test that use change an swap pillar.
By any chance why move selector benchmarks almost never do steps?
> Create multi pillar tests

- drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/cep/SlidingTimeWindowBenchmark.java
JIRA: https://issues.redhat.com/browse/DROOLS-7328
Releted to this https://github.com/kiegroup/drools/pull/5032
> [DROOLS-7328] sliding time window benchmark

- optaplanner-benchmarks/pom.xml
Generated by build jenkins-KIE-optaplanner-main-setup-branch-optaplanner-8: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/setup-branch/job/optaplanner/8/
> bumped up Optaplanner version to next SNAPSHOT

- optaplanner-benchmarks/pom.xml
Generated by build jenkins-KIE-optaplanner-main-tools-kie-benchmarks-update-optaplanner-1: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/tools/job/kie-benchmarks-update-optaplanner/1/
> bumped up optaplanner version to 8.39.0-SNAPSHOT

- optaplanner-benchmarks/pom.xml
Generated by build jenkins-KIE-optaplanner-main-tools-kie-benchmarks-update-optaplanner-2: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/tools/job/kie-benchmarks-update-optaplanner/2/
> bumped up optaplanner version to 8.40.0-SNAPSHOT

- optaplanner-benchmarks/pom.xml
Generated by build jenkins-KIE-optaplanner-main-tools-kie-benchmarks-update-optaplanner-3: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/tools/job/kie-benchmarks-update-optaplanner/3/
> bumped up optaplanner version to 8.41.0-SNAPSHOT

- optaplanner-benchmarks/pom.xml
Generated by build jenkins-KIE-optaplanner-main-tools-kie-benchmarks-update-optaplanner-4: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/tools/job/kie-benchmarks-update-optaplanner/4/
> bumped up optaplanner version to 8.42.0-SNAPSHOT

- optaplanner-benchmarks/pom.xml
Generated by build jenkins-KIE-optaplanner-main-tools-kie-benchmarks-update-optaplanner-6: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/tools/job/kie-benchmarks-update-optaplanner/6/
> bumped up optaplanner version to 8.43.0-SNAPSHOT

- optaplanner-benchmarks/pom.xml
Generated by build jenkins-KIE-optaplanner-main-tools-kie-benchmarks-update-optaplanner-7: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/tools/job/kie-benchmarks-update-optaplanner/7/
> bumped up optaplanner version to 8.44.0-SNAPSHOT

- drools-benchmarks-parent/drools-benchmarks-reliability/src/main/java/org/drools/benchmarks/reliability/AbstractReliabilityBenchmark.java
- drools-benchmarks-parent/drools-benchmarks-reliability/src/main/java/org/drools/benchmarks/reliability/FireAndAlarmBenchmark.java
- drools-benchmarks-parent/drools-benchmarks-reliability/src/main/java/org/drools/benchmarks/reliability/fireandalarm/Alarm.java
- drools-benchmarks-parent/drools-benchmarks-reliability/src/main/java/org/drools/benchmarks/reliability/fireandalarm/Fire.java
- drools-benchmarks-parent/drools-benchmarks-reliability/src/main/java/org/drools/benchmarks/reliability/fireandalarm/Room.java
- drools-benchmarks-parent/drools-benchmarks-reliability/src/main/java/org/drools/benchmarks/reliability/fireandalarm/Sprinkler.java
the PR introduces a simple benchmark for opt-in object store with references: 
* benchmark FireAndAlarm.java
> [DROOLS-7539] FireAndAlarmBenchmark

- .ci/jenkins/Jenkinsfile.branch
- .ci/jenkins/Jenkinsfile.bump-up-version
Fixing references for kie-docs and kie-benchmarks repositories.
> Fix CI references to kie-docs and kie-benchmarks

- .ci/jenkins/Jenkinsfile.branch
- .ci/jenkins/Jenkinsfile.bump-up-version
part of https://github.com/apache/incubator-kie-issues/issues/777
> kie-issues#777: Allow restricting jenkins agent labels for pipelines

- drools-benchmarks-parent/drools-benchmarks/README.md
Add explanation about flamegraphs file generation
> [NO_ISSUE] Documenting Flamegraphs generation
