apache/incubator-kie-benchmarks

drools-benchmarks/src/main/java/org/drools/benchmarks/common/ConstraintPattern.java
drools-benchmarks/src/main/java/org/drools/benchmarks/common/providers/RulesWithJoinsTreeProvider.java
drools-benchmarks/src/main/java/org/drools/benchmarks/common/util/TestUtil.java
drools-benchmarks/src/main/java/org/drools/benchmarks/session/InsertFireCancelSecondRuleBenchmark.java
drools-benchmarks/src/main/java/org/drools/benchmarks/session/RuleUnlinkingBenchmark.java

Added benchmark is required to measure the cost of unlinking
vs. size of crossproduct.

Adds benchmark InsertFireCancelSecondRuleBenchmark

---

drools-benchmarks/src/main/java/org/drools/benchmarks/turtle/runtime/TurtleBenchmarkRunner.java
drools-benchmarks/src/main/java/org/drools/benchmarks/turtle/runtime/TurtleFusionBenchmarkRunner.java

Added runners can be used to debug benchmarks outside of JMH.

Add runners for turtle runtime benchmarks

---

drools-benchmarks/src/main/java/org/drools/benchmarks/oopath/AbstractOOPathComparisonBenchmark.java
drools-benchmarks/src/main/java/org/drools/benchmarks/oopath/OOPathComparisonFromVariationInsertBenchmark.java
drools-benchmarks/src/main/java/org/drools/benchmarks/oopath/OOPathComparisonFromVariationUpdateBenchmark.java
drools-benchmarks/src/main/java/org/drools/benchmarks/oopath/OOPathComparisonOOpathVariationInsertBenchmark.java
drools-benchmarks/src/main/java/org/drools/benchmarks/oopath/OOPathComparisonOOpathVariationUpdateBenchmark.java
drools-benchmarks/src/main/java/org/drools/benchmarks/oopath/OOPathComparisonRelationalVariationInsertBenchmark.java
drools-benchmarks/src/main/java/org/drools/benchmarks/oopath/OOPathComparisonRelationalVariationUpdateBenchmark.java
drools-benchmarks/src/main/java/org/drools/benchmarks/oopath/model/Adult.java
drools-benchmarks/src/main/java/org/drools/benchmarks/oopath/model/BodyMeasurement.java
drools-benchmarks/src/main/java/org/drools/benchmarks/oopath/model/Child.java
drools-benchmarks/src/main/java/org/drools/benchmarks/oopath/model/Disease.java
drools-benchmarks/src/main/java/org/drools/benchmarks/oopath/model/Man.java
drools-benchmarks/src/main/java/org/drools/benchmarks/oopath/model/Person.java
drools-benchmarks/src/main/java/org/drools/benchmarks/oopath/model/Toy.java
drools-benchmarks/src/main/java/org/drools/benchmarks/oopath/model/Woman.java

Add benchmarks that replace class OOPathBenchmarkTest [1] from
Drools repository
I will merge this when reviewed. 
[1] https://github.com/kiegroup/drools/blob/master/drools-compiler/src/test/java/org/drools/compiler/oopath/OOPathBenchmarkTest.java

Add OOPath comparative benchmarks

---

optaplanner-benchmarks/optaplanner-perf-benchmark/src/main/java/org/jboss/qa/brms/performance/realworld/vrp/VehicleRoutingBenchmark.java
optaplanner-benchmarks/optaplanner-perf-framework/src/main/resources/org/jboss/qa/brms/performance/examples/vrp/solver/vehicleRoutingScoreRules.drl

Tweaked solver config to scan annotated classes from VRP domain, unlike [original](https://github.com/Fonifan/optaplanner/blob/master/optaplanner-examples/src/main/resources/org/optaplanner/examples/vehiclerouting/solver/vehicleRoutingSolverConfig.xml) (from optaplanner-examples ) solver config, which has hardcoded classes.

PLANNER-1374: Add Vehicle Routing real world benchmark

---

jbpm-benchmarks/jbpm-performance-tests/pom.xml

This was missing Hibernate alignment that was done as part of main repos.

Align persistence dependencies with kie-parent

---

optaplanner-benchmarks/pom.xml
pom.xml

Revert of f817bb553628cb9ec0795ee608a27161a0f4b745 and deletion of a duplicate declaration in the ` optaplanner-benchmarks` module

Reintroduce kie-platform-bom

---

pom.xml

Despite the fact that the script I introduced yesterday correctly replaced the version, tests still fail. The reason is KIE artifacts' versions are not defined in kie-parent anymore, but in kie-platform-bom. We already use it on master branch
This PR introduced kie-platform-bom to 7.26.x branch. Compilation passed locally with bxms nexus and public-pnc nexus group.

Use kie-platform-bom again

---

jbpm-benchmarks/jbpm-performance-tests/run.sh
jbpm-benchmarks/kieserver-performance-tests/run.sh

After the introduction of the #61 I no longer need to override the `version.org.kie` property. I have already tested it with all perf jobs.

Remove version parameter from run.sh scripts

---

drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/runtime/DMNEvaluateTriangularNumHardBenchmark.java

now baseline:
```
Benchmark                                              (numberOfDecisionsWithContext)  Mode  Cnt  Score   Error  Units
DMNEvaluateTriangularNumHardBenchmark.evaluateContext                              20    ss  500  0.190 ± 0.005  ms/op
DMNEvaluateTriangularNumHardBenchmark.evaluateContext                              50    ss  500  0.330 ± 0.008  ms/op
```
@baldimir

Tuning parameters to improve accuracy for DMNEvaluateTriangularNumHard..

---

drools-benchmarks/src/main/java/org/drools/benchmarks/common/util/BuildtimeUtil.java

Since the new default is use executable model, we need to set the old behaviour as an argument to the buildAll function.

BAQE-1226 - Drools Buildtime benchmark regression

---

optaplanner-benchmarks/optaplanner-perf-benchmark/src/main/java/org/jboss/qa/brms/performance/AbstractPlannerBenchmark.java
optaplanner-benchmarks/optaplanner-perf-benchmark/src/main/java/org/jboss/qa/brms/performance/score/constraintstream/TravelingTournamentConstraintStreamsBenchmark.java
optaplanner-benchmarks/optaplanner-perf-framework/data/travelingtournament/4-super06.xml
optaplanner-benchmarks/optaplanner-perf-framework/data/travelingtournament/4-super10.xml
optaplanner-benchmarks/optaplanner-perf-framework/data/travelingtournament/4-super14.xml
optaplanner-benchmarks/optaplanner-perf-framework/src/main/java/org/jboss/qa/brms/performance/examples/Examples.java
optaplanner-benchmarks/optaplanner-perf-framework/src/main/java/org/jboss/qa/brms/performance/examples/travelingtournament/TravelingTournamentExample.java
optaplanner-benchmarks/optaplanner-perf-framework/src/main/java/org/jboss/qa/brms/performance/examples/travelingtournament/persistance/TravelingTournamentDao.java
optaplanner-benchmarks/optaplanner-perf-framework/src/main/resources/org/jboss/qa/brms/performance/examples/travelingtournament/solver/travelingTournamentSolverConfig.xml

In addition to the benchmark, I've adjusted the default jmh params to comply with other examples.

Add a constraint stream benchmark for Traveling tournament example

---

jbpm-benchmarks/kieserver-performance-tests/pom.xml

Import scope no longer needed after WildFly JMS Client BOM consolidation.

JBPM-9044 - Upgrade kiegroup repos to Wildfly 18.0.1.Final

---

drools-benchmarks/src/main/resources/turtle/expert-basic-insert-logical-facts-into-wm-1000.drl

Removed comments from DRL file.
Job blessed-perf-turtle-runtime-benchmarks is failing randomly and an issue was filed to investigate it (BAQE-1221). During the investigation, it was noticed during the failure was connected with multiples comments in the DRL resource file (expert-basic-insert-logical-facts-into-wm-1000.drl). It is happening only when running with JMH, not reproducible with Junit. Since this job runs nightly, it needs to be stabilized until the root cause and solution are found.
Note: comments are sharing the same row with some code (e.g. code; //comment).
This PR is being sent after 30 executions [1] that might confirm this behaviour, but it is still just an attempt to make the nightly jobs go green.
[1] https://rhba-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job …

BAQE-1557-Stabilize blessed-perf-turtle-runtime-benchmarks

---

drools-benchmarks/src/main/java/org/drools/benchmarks/common/util/DummyProcessRuntime.java

Build is failing due to new methods added on ProcessRuntime interface.

BAQE-1593 - Implement added methods on DummyProcessRuntime

---

pom.xml

This upgrade allows us to use the async-profiler [1] which integration was recently implemented on JMH.
[1] https://github.com/jvm-profiling-tools/async-profiler

BAQE-1592 - Upgrade kie-benchmarks to JMH 1.26

---

drools-benchmarks/pom.xml

Descoping ECJ from Drools (DROOLS-5780) caused OOM error in Drools benchmarks.

BAQE-1611 - fix ecj dependency in drools benchmarks

---

jbpm-benchmarks/jbpm-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LParallelGatewayTwoTimesProcess.java
jbpm-benchmarks/kieserver-performance-tests/pom.xml
jbpm-benchmarks/kieserver-performance-tests/run.sh

BAQE-1706 - Fix of JBPM and Kie Server tests on jdk11. Needs to be merged together with drools-integration PR as well as edit to bxms-qe-tests.

BAQE-1706 - Fix of JBPM and Kie Server tests on jdk11

---

drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/example/DMNCH11ExampleBenchmark.java
drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/util/DynamicTypeUtils.java

supporting data and evidence for DROOLS-4605 just one of many, but
providing it as a kie-benchmark form.
ref: https://issues.redhat.com/browse/DROOLS-6237
```
Benchmark                         (useExecModelCompiler)  Mode  Cnt  Score   Error  Units
DMNCH11ExampleBenchmark.evaluate                    true    ss  500  2.594 ± 0.059  ms/op
DMNCH11ExampleBenchmark.evaluate                   false    ss  500  1.337 ± 0.021  ms/op
```
as run locally.

DROOLS-6237 DMN benchmark supporting evidence

---

jbpm-benchmarks/jbpm-performance-tests-jmh/pom.xml
jbpm-benchmarks/jbpm-performance-tests/pom.xml
jbpm-benchmarks/kieserver-performance-tests/pom.xml

This commit solves dependency issues introduced by moving to jakarta apis as a part of upgrade to wildfly 23:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/commit/269da3638455a03becc7a10f8db7989a858536c4#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8

BAQE-2017 - Adapt kie-benchmarks to move to jakarta apis

---

optaplanner-7-benchmarks/optaplanner-perf-benchmark/src/main/java/org/jboss/qa/brms/performance/realworld/cloudbalancing/CloudBalanceBenchmark.java
optaplanner-7-benchmarks/optaplanner-perf-benchmark/src/main/java/org/jboss/qa/brms/performance/realworld/vrp/VehicleRoutingBenchmark.java
optaplanner-7-benchmarks/optaplanner-perf-framework/src/main/java/org/jboss/qa/brms/performance/examples/conferencescheduling/ConferenceSchedulingExample.java
optaplanner-7-benchmarks/optaplanner-perf-framework/src/main/resources/org/jboss/qa/brms/performance/examples/conferencescheduling/solver/conferenceSchedulingSolverConfig.xml

Fixes for performance benchmarks according to example data set changes
Accidentally changed it in the wrong branch here 7540e42ffa535e7f6bc90da99830f9cdc7bddbfc 
https://qe-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/blue/organizations/jenkins/TESTING%2F_upstream%2Fconstraint_solving%2F7.x%2Fperf-optaplanner-upstream/detail/perf-optaplanner-upstream/19/pipeline

Path fixes for OptaPlanner 7.x

---

.github/workflows/pull_request_8.x.yml
optaplanner-8-benchmarks/optaplanner-perf-benchmark/pom.xml
optaplanner-8-benchmarks/optaplanner-perf-benchmark/src/main/java/org/jboss/qa/brms/performance/construction/tsp/TSPConstructionBenchmark.java
optaplanner-8-benchmarks/optaplanner-perf-benchmark/src/main/java/org/jboss/qa/brms/performance/realworld/cloudbalancing/CloudBalanceBenchmark.java
optaplanner-8-benchmarks/optaplanner-perf-benchmark/src/main/java/org/jboss/qa/brms/performance/realworld/conferencescheduling/ConferenceSchedulingBenchmark.java
optaplanner-8-benchmarks/optaplanner-perf-benchmark/src/main/java/org/jboss/qa/brms/performance/realworld/nurserostering/NurseRosteringBenchmark.java
optaplanner-8-benchmarks/optaplanner-perf-benchmark/src/main/java/org/jboss/qa/brms/performance/score/constraintstream/FlightCrewSchedulingConstraintStreamsBenchmark.java
optaplanner-8-benchmarks/optaplanner-perf-benchmark/src/main/java/org/jboss/qa/brms/performance/score/constraintstream/TravelingTournamentConstraintStreamsBenchmark.java
optaplanner-8-benchmarks/optaplanner-perf-benchmark/src/main/java/org/jboss/qa/brms/performance/score/constraintstream/VehicleRoutingConstraintStreamsBenchmark.java
optaplanner-8-benchmarks/optaplanner-perf-benchmark/src/test/java/org/jboss/qa/brms/performance/SolverConfigFromXmlTest.java
optaplanner-8-benchmarks/optaplanner-perf-benchmark/src/test/resources/logback-test.xml
optaplanner-8-benchmarks/optaplanner-perf-framework/src/main/java/org/jboss/qa/brms/performance/examples/cloudbalancing/CloudBalancingExample.java
optaplanner-8-benchmarks/optaplanner-perf-framework/src/main/java/org/jboss/qa/brms/performance/examples/conferencescheduling/ConferenceSchedulingExample.java
optaplanner-8-benchmarks/optaplanner-perf-framework/src/main/java/org/jboss/qa/brms/performance/examples/tsp/TravelingSalesmanExample.java
optaplanner-8-benchmarks/optaplanner-perf-framework/src/main/java/org/jboss/qa/brms/performance/persistence/AbstractSolutionDao.java
optaplanner-8-benchmarks/optaplanner-perf-framework/src/main/resources/org/jboss/qa/brms/performance/examples/tsp/solver/tspSolverConfig.xml

When optaplanner examples are change then the benchmarks fails during runtime
Added SolverConfigFromXmlTest.java to catch it during build time
Added constractors default and parametrized to initialize benchmarks with DataSet
Changed dataSet to dataset
fixed tspSolverConfig.xml
PR suggestion to load the data
Add solver config test
Add Test that will catch runtime exceptions if solver config xml file would need to change path to the xml files

Add param test for checking package location of xml solver config

---

jbpm-benchmarks/jbpm-performance-tests-jmh/pom.xml
jbpm-benchmarks/jbpm-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/L1000HumanTasksComplete.java
jbpm-benchmarks/jbpm-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/L1000HumanTasksQueryPagination.java
jbpm-benchmarks/jbpm-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/L1000HumanTasksStart.java
jbpm-benchmarks/jbpm-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/L1000ProcessesSignal.java
jbpm-benchmarks/jbpm-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LGroupHumanTaskProcess.java
jbpm-benchmarks/jbpm-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LHumanTaskProcess.java
jbpm-benchmarks/jbpm-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LHumanTaskProcessWithListeners.java
jbpm-benchmarks/jbpm-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LIntermediateSignalProcess.java
jbpm-benchmarks/jbpm-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LParallelGatewayProcess.java
jbpm-benchmarks/jbpm-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LParallelGatewayTenTimesProcess.java
jbpm-benchmarks/jbpm-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LParallelGatewayTwoTimesProcess.java
jbpm-benchmarks/jbpm-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LRuleTaskProcess.java
jbpm-benchmarks/jbpm-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LScriptTaskProcess.java
jbpm-benchmarks/jbpm-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LStartEndProcess.java
jbpm-benchmarks/kieserver-performance-tests-jmh/pom.xml
jbpm-benchmarks/kieserver-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LServerGroupHumanTaskProcess.java
jbpm-benchmarks/kieserver-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LServerHumanTaskProcess.java
jbpm-benchmarks/kieserver-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LServerParallelGatewayTwoTimesProcess.java
jbpm-benchmarks/kieserver-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LServerRuleTaskProcess.java
jbpm-benchmarks/kieserver-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LServerStartEndNoCheckProcess.java
jbpm-benchmarks/kieserver-performance-tests-jmh/src/main/java/org/jbpm/test/performance/scenario/load/LServerStartEndProcess.java
jbpm-benchmarks/perf-tests-common/pom.xml
jbpm-benchmarks/perf-tests-common/src/main/java/org/jbpm/test/performance/test/common/AbstractJmhTest.java
jbpm-benchmarks/perf-tests-common/src/main/java/org/jbpm/test/performance/test/common/PerfdbClean.java
jbpm-benchmarks/pom.xml
pom.xml

Invoking sql-maven-plugin to drop and create schema in TearDown method of each test scenario so the DB is always fresh.
Needs to be merged **after** adapting JobDSLs to this change.

BAQE-2134 - Db cleaning in Teardown method of JMH tests

---

drools-benchmarks/pom.xml
optaplanner-benchmarks/pom.xml

-restore the version.org.{product} property to allow the benchmarks to be launched from the kogito CR pipeline

BAQE-2275 - kie-benchmarks repository reorganization (main branch) - fix versioning

---

drools-benchmarks/pom.xml
drools-benchmarks/src/main/java/org/drools/benchmarks/common/util/DummyProcessRuntime.java
drools-benchmarks/src/main/java/org/drools/benchmarks/common/util/TestUtil.java
optaplanner-benchmarks/optaplanner-perf-benchmark/pom.xml
optaplanner-benchmarks/optaplanner-perf-framework/pom.xml
optaplanner-benchmarks/pom.xml
pom.xml

bump to 8.21.0-SNAPSHOT + fix compilation failures caused by DROOLS-6036 (isolate commands in their own module) made on 8.21.0-SNAPSHOT version of Drools

bump to 8.21.0-SNAPSHOT + fix compilation failures caused by DROOLS-6036

---

drools-benchmarks/src/main/java/org/drools/benchmarks/session/FirstResponseBenchmark.java

https://issues.redhat.com/browse/DROOLS-6988
Local result:
```
Benchmark                    (factsNr)  (rulesNr)  (useCanonicalModel)  Mode  Cnt       Score      Error  Units
FirstResponseBenchmark.test         10         64                 true    ss  100   60004.855 ± 2796.496  us/op
FirstResponseBenchmark.test         10         64                false    ss  100  152638.669 ± 6430.676  us/op
```

[DROOLS-6988] First response time benchmark

---

drools-benchmarks-parent/drools-benchmarks-module/.gitignore
drools-benchmarks-parent/drools-benchmarks-module/pom.xml
drools-benchmarks-parent/drools-benchmarks-module/src/main/resources/META-INF/kmodule.xml
drools-benchmarks-parent/drools-benchmarks-module/src/main/resources/dmn/Traffic Violation.dmn
drools-benchmarks-parent/drools-benchmarks-module/src/main/resources/dmn/abigone.dmn
drools-benchmarks-parent/drools-benchmarks-module/src/main/resources/dmn/ch11MODIFIED.dmn
drools-benchmarks-parent/drools-benchmarks-module/src/main/resources/drl/rules.drl
drools-benchmarks-parent/drools-benchmarks-module/src/main/resources/drl/rules_simple.drl
drools-benchmarks-parent/drools-benchmarks-quick/README.md
drools-benchmarks-parent/drools-benchmarks-quick/pom.xml
drools-benchmarks-parent/drools-benchmarks-quick/src/main/java/org/drools/benchmarks/quick/InstantiateKieContainerFromKJarBenchmark.java
drools-benchmarks-parent/drools-benchmarks-quick/src/main/resources/logback.xml
drools-benchmarks-parent/pom.xml

Fixes https://github.com/kiegroup/kie-issues/issues/53
@baldimir @danielezonca @hellowdan 
This PR
1. creates a stand-alone "drools-benchmarks-module" to be used for benchmarks
2. creates `InstantiateKieContainerFromKJarBenchmark` to measure instantiation time of `KieContainer`
Notes:
1.  `KieServices.newKieContainer(ReleaseId releaseId, ClassLoader classLoader)` has been used because, locally, the usage of `KieServices.newKieContainer(ReleaseId releaseId);` throws `ArtifactNotFoundExcpetions` inside JHM; apparently, in that case `MavenClassLoaderResolver`  does not properly replace version placeholders
2.  `KieContainer.getKieBase(String kBaseName)`  is invoked to verify that the required module has actually been found and loaded

[kie-issues#53] Implement KieContainer load time benchmark

---

drools-benchmarks-parent/drools-benchmarks-quick/src/main/java/org/drools/benchmarks/quick/CommonProperties.java
drools-benchmarks-parent/drools-benchmarks-quick/src/main/java/org/drools/benchmarks/quick/InstantiateKJarBenchmark.java
drools-benchmarks-parent/drools-benchmarks-quick/src/main/java/org/drools/benchmarks/quick/InstantiateKieContainerFromKJarBenchmark.java
drools-benchmarks-parent/drools-benchmarks-quick/src/main/java/org/drools/benchmarks/quick/InstantiateKieJarBenchmark.java

@baldimir @mariofusco  @danielezonca 
Fixes https://github.com/kiegroup/kie-issues/issues/52
I've implemented `InstantiateKieJarBenchmark` following code from `BuildKJarFromResourceBenchmark`
The `Setup` phase read file content as string and uses `ByteArrayResource` to avoid possible unrelated IO issues during benchmark execution

[kie-issues#52] WIP - Quick kjar build-time

---

optaplanner-benchmarks/pom.xml

Generated by build jenkins-KIE-optaplanner-main-setup-branch-optaplanner-9: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/main/job/setup-branch/job/optaplanner/9/

bumped up Optaplanner version to next SNAPSHOT

---

drools-benchmarks-parent/README.md
drools-benchmarks-parent/drools-benchmarks-common/src/main/java/org/drools/benchmarks/common/model/AbstractBean.java
drools-benchmarks-parent/drools-benchmarks-reliability/.gitignore
drools-benchmarks-parent/drools-benchmarks-reliability/README.md
drools-benchmarks-parent/drools-benchmarks-reliability/pom.xml
drools-benchmarks-parent/drools-benchmarks-reliability/src/main/java/org/drools/benchmarks/reliability/AbstractReliabilityBenchmark.java
drools-benchmarks-parent/drools-benchmarks-reliability/src/main/java/org/drools/benchmarks/reliability/FireOnlyBenchmark.java
drools-benchmarks-parent/drools-benchmarks-reliability/src/main/java/org/drools/benchmarks/reliability/InsertOnlyBenchmark.java
drools-benchmarks-parent/drools-benchmarks-reliability/src/main/resources/logback.xml
drools-benchmarks-parent/pom.xml

Local test results
```
Benchmark                 (factsNr)  (joinsNr)    (mode)  (rulesNr)  Mode  Cnt    Score   Error  Units
FireOnlyBenchmark.test           10        N/A      NONE        192    ss  200    1.474 ± 0.090  ms/op
FireOnlyBenchmark.test           10        N/A  EMBEDDED        192    ss  200    2.408 ± 0.117  ms/op
FireOnlyBenchmark.test           10        N/A    REMOTE        192    ss  200    2.842 ± 0.235  ms/op
FireOnlyBenchmark.test          100        N/A      NONE        192    ss  200    4.901 ± 0.216  ms/op
FireOnlyBenchmark.test          100        N/A  EMBEDDED        192    ss  200    7.799 ± 0.201  ms/op
FireOnlyBenchmark.test          100        N/A    REMOTE        192    ss  200   12.299 ± 0.287  ms/op
FireOnlyBenchmark.test         1000        N/A …
```

[DROOLS-7361] Add benchmarks for drools-reliability

---

drools-benchmarks-parent/pom.xml

Generated by build jenkins-KIE-drools-main-tools-kie-benchmarks-update-drools-1: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/tools/job/kie-benchmarks-update-drools/1/

bumped up drools version to 8.39.0-SNAPSHOT

---

drools-benchmarks-parent/drools-benchmarks-reliability/src/main/java/org/drools/benchmarks/reliability/AbstractReliabilityBenchmark.java

Follow up on drools-reliability renaming from Cache to Storage : https://github.com/kiegroup/drools/pull/5184

Follow up on drools-reliability renaming from Cache to Storage

---

drools-benchmarks-parent/drools-benchmarks-reliability/src/main/java/org/drools/benchmarks/reliability/InsertAndFireBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/turtle/runtime/AdvOperators2ExpertBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/turtle/runtime/AdvOperators3ExpertBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/turtle/runtime/AdvOperators4ExpertBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/turtle/runtime/AdvOperatorsExpertBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/turtle/runtime/AfterBeforeFusionBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/turtle/runtime/CoincidesDuringFusionBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/turtle/runtime/DTable1Benchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/turtle/runtime/DTable2Benchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/turtle/runtime/FinishesFinishedbyFusionBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/turtle/runtime/InsertFactsIntoWmExpertBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/turtle/runtime/InsertLogicalFactsIntoWmExpertBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/turtle/runtime/MeetsMetbyFusionBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/turtle/runtime/OverlapsOverlappedbyFusionBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/turtle/runtime/RetractFactsFromWmExpertBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/turtle/runtime/SimpleDummyFactsMatchRatioExpertBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/turtle/runtime/StandardOperatorsExpertBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/turtle/runtime/StartsStartedbyFusionBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/turtle/runtime/UpdateFactsInWmExpertBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/turtle/runtime/WmManipulationExpertBenchmark.java

Similar change as at https://github.com/kiegroup/kie-benchmarks/commit/f4f8944dff46718796d633ed7abe8ffd055c15b7
Adding parameters to have consistent  json report

Param fix for runtime benchmarks

---

drools-benchmarks-parent/drools-benchmarks-quick/pom.xml
drools-benchmarks-parent/drools-benchmarks-reliability/pom.xml
drools-benchmarks-parent/drools-benchmarks/pom.xml
drools-benchmarks-parent/pom.xml
optaplanner-benchmarks/optaplanner-perf-benchmark/pom.xml

**JIRA**: https://issues.redhat.com/browse/DROOLS-7456
**referenced Pull Requests**: 
* requires first a new version of MVEL: https://github.com/mvel/mvel/pull/330
* https://github.com/kiegroup/drools/pull/5267
* https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/48
* https://github.com/kiegroup/kie-benchmarks/pull/245
**Details**:
* drools-ecj is de-shaded, so shading `ECJ` as a dependency the new version containing checksum requires dropping these files from the `ECJ artifact` when building the bundled uber-jar / fat jar creation.

DROOLS-7456 avoid kie maven plugin to crash on jdk17 project

---

drools-benchmarks-parent/pom.xml

Generated by build jenkins-KIE-drools-main-tools-kie-benchmarks-update-drools-3: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/tools/job/kie-benchmarks-update-drools/3/

bumped up drools version to 8.41.0-SNAPSHOT

---

drools-benchmarks-parent/pom.xml

When running jmh test it takes the project by version. The version could contain number of commits.
This plugin copies core dependency to allow faster access to the MANIFEST file
/drools-parent/target/dependency/drools-core.jar/META-INF/MANIFEST.MF

Add maven-dependency-plugin:copy-dependencies

---

drools-benchmarks-parent/pom.xml

Generated by build jenkins-KIE-drools-main-tools-kie-benchmarks-update-drools-4: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/tools/job/kie-benchmarks-update-drools/4/

bumped up drools version to 8.42.0-SNAPSHOT

---

drools-benchmarks-parent/pom.xml

Generated by build jenkins-KIE-drools-main-tools-kie-benchmarks-update-drools-5: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/tools/job/kie-benchmarks-update-drools/5/

bumped up drools version to 8.43.0-SNAPSHOT

---

drools-benchmarks-parent/pom.xml

Generated by build jenkins-KIE-drools-main-tools-kie-benchmarks-update-drools-6: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/tools/job/kie-benchmarks-update-drools/6/

bumped up drools version to 8.44.0-SNAPSHOT

---

.ci/jenkins/Jenkinsfile.branch
.ci/jenkins/Jenkinsfile.bump-up-version
.ci/jenkins/dsl/jobs.groovy
.ci/jenkins/dsl/test.sh

@jstastny-cz I added one more commit, see 2bb0a165e7ee1811cc48f3a8c82396b306f9e33f to fix the repository name. If I understood it correctly, it should reference the new repository name too. Otherwise it would still check out the kiegroup mirror.
- https://github.com/kiegroup/kogito-pipelines/pull/1078
- https://github.com/kiegroup/kogito-runtimes/pull/3223
- https://github.com/kiegroup/kogito-examples/pull/1806
- https://github.com/kiegroup/kogito-apps/pull/1877
- https://github.com/kiegroup/kogito-images/pull/1698
- https://github.com/kiegroup/kogito-operator/pull/1528
- https://github.com/kiegroup/kogito-serverless-operator/pull/250
- https://github.com/kiegroup/kogito-docs/pull/497
- https://github.com/kiegroup/drools/pull/5519
- https://github.com/kiegroup/drools-website/pull/269
- …

Update `kiegroup` repository references to `apache`

---

.ci/jenkins/Jenkinsfile.branch
.ci/jenkins/Jenkinsfile.bump-up-version
.ci/jenkins/dsl/jobs.groovy
.ci/jenkins/dsl/test.sh

apache/incubator-kie-kogito-pipelines#1090
apache/incubator-kie-kogito-runtimes#3233
apache/incubator-kie-kogito-apps#1882
apache/incubator-kie-kogito-examples#1810
apache/incubator-kie-kogito-images#1703
apache/incubator-kie-kogito-operator#1530
apache/incubator-kie-kogito-serverless-operator#257
apache/incubator-kie-kogito-docs#504
apache/incubator-kie-docs#4529
apache/incubator-kie-drools#5531
apache/incubator-kie-optaplanner#2985
apache/incubator-kie-optaplanner-quickstarts#607
apache/incubator-kie-benchmarks#262

kie-issues#574 Initial ASF Jenkins CI Setup

---

jbpm-benchmarks/kieserver-assets/src/main/resources/processes/HumanTaskNotification.bpmn2
jbpm-benchmarks/kieserver-performance-tests-jmh-manual/pom.xml
jbpm-benchmarks/kieserver-performance-tests-jmh-manual/src/main/java/org/jbpm/test/performance/scenario/load/LServerHumanTaskNotificationProcess.java
jbpm-benchmarks/kieserver-performance-tests-jmh/src/main/java/org/jbpm/test/performance/kieserver/constant/ProcessStorage.java

This is a benchmark test that has to be run manually, as described in https://github.com/kiegroup/kie-benchmarks/pull/173
The additional test uses a simple process containing one human task with a notification at `#{timerDuration}`. The test starts the process with timerDuration set to 10d, and does not complete it, as the idea is to measure (and compare) the time it takes such a process if the database contains a high number of timers.
Local test results:
Test run with an empty DB (postgresql):
```
Benchmark                                        (remoteAPI)  Mode  Cnt  Score   Error  Units
LServerHumanTaskNotificationProcess.AverageTime         REST  avgt   10  0.401 ± 0.130   s/op
LServerHumanTaskTimerProcess.AverageTime                REST  avgt   10  0.769 ± 0.577   s/op
```
Test run …

[RHPAM-4698] Benchmark test for task notifications

---

drools-benchmarks-parent/drools-benchmarks-reliability/pom.xml
drools-benchmarks-parent/drools-benchmarks-reliability/src/main/java/org/drools/benchmarks/reliability/AbstractReliabilityBenchmark.java
drools-benchmarks-parent/drools-benchmarks-reliability/src/main/java/org/drools/benchmarks/reliability/AbstractReliabilityBenchmarkFailoverSupport.java
drools-benchmarks-parent/drools-benchmarks-reliability/src/main/java/org/drools/benchmarks/reliability/FireAndAlarmBenchmark.java
drools-benchmarks-parent/drools-benchmarks-reliability/src/main/java/org/drools/benchmarks/reliability/InsertFailoverFireBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/turtle/runtime/AbstractSimpleFusionRuntimeBenchmark.java

[DROOLS-7543](https://issues.redhat.com/browse/DROOLS-7543)

DROOLS-7543 : benchmark to test session restore after failover

---

drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/session/ExecuteStatelessSessionBenchmark.java

Benchmark for https://github.com/apache/incubator-kie-issues/issues/635

[KIE-635] add a benchmark for stateless session execution

---

drools-benchmarks-parent/drools-benchmarks-reliability/pom.xml
drools-benchmarks-parent/drools-benchmarks-reliability/src/main/java/org/drools/benchmarks/reliability/AbstractReliabilityBenchmark.java
drools-benchmarks-parent/drools-benchmarks-reliability/src/main/java/org/drools/benchmarks/reliability/FireAndAlarmBenchmark.java
drools-benchmarks-parent/drools-benchmarks-reliability/src/main/java/org/drools/benchmarks/reliability/InsertFailoverFireBenchmark.java

[DROOLS-7573](https://issues.redhat.com/browse/DROOLS-7573)

DROOLS-7573 - add parameter for h2vm/infinispan store

---

drools-benchmarks-parent/drools-benchmarks-common/src/main/java/org/drools/benchmarks/common/model/A.java
drools-benchmarks-parent/drools-benchmarks-common/src/main/java/org/drools/benchmarks/common/model/B.java
drools-benchmarks-parent/drools-benchmarks-common/src/main/java/org/drools/benchmarks/common/providers/RulesWithJoinsProvider.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/concurrent/ConcurrentUpdateLeftTupleBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/concurrent/ConcurrentUpdateRightTupleBenchmark.java

- ConcurrentUpdateRightTupleBenchmark calls RightTupleImpl.getTupleSink() a lot
- ConcurrentUpdateLeftTupleBenchmark calls LeftTuple.getTupleSink() a lot

[DROOLS-7576] Add benchmarks for secondary super cache issue

---

.ci/jenkins/Jenkinsfile.branch
.ci/jenkins/Jenkinsfile.bump-up-version

apache/incubator-kie-issues#667
Fixing cleanup and settings.xml pipeline configuration to work correctly in ASF Jenkins.
* Deferred wipeout was causing issues when invoked in early stages
* Docker cleanup can't be done since the overall build is in docker container that uses the docker.sock from the host - it would attempt to erase itself.
* withSettingsXmlId shared library method does imply usage of a prohibited groovy method, thus replacing with explicit configFileProvider and passing as withSettingsXmlFile goes around that part of code. 
Complete list:
apache/incubator-kie-kogito-pipelines#1113
apache/incubator-kie-kogito-runtimes#3272
apache/incubator-kie-kogito-apps#1909
apache/incubator-kie-kogito-examples#1820
apache/incubator-kie-drools#5572
apache/incubator-kie-optaplanner#3010 …

kie-issues#667: fix cleanup and settingsXml handling

---

drools-benchmarks-parent/pom.xml

Generated by build jenkins-KIE-drools-main-tools-kie-benchmarks-update-drools-3: https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/tools/job/kie-benchmarks-update-drools/3/

bumped up drools version to 8.46.0-SNAPSHOT

---

drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/feel/FEELInfixOpBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/feel/infixexecutors/FEELAddExecutorBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/feel/infixexecutors/FEELAndExecutorBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/feel/infixexecutors/FEELDivExecutorBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/feel/infixexecutors/FEELEqExecutorBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/feel/infixexecutors/FEELGtExecutorBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/feel/infixexecutors/FEELGteExecutorBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/feel/infixexecutors/FEELInfixExecutorBenchmarkUtils.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/feel/infixexecutors/FEELLtExecutorBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/feel/infixexecutors/FEELLteExecutorBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/feel/infixexecutors/FEELMultExecutorBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/feel/infixexecutors/FEELNeExecutorBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/feel/infixexecutors/FEELOrExecutorBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/feel/infixexecutors/FEELPowExecutorBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/feel/infixexecutors/FEELSubExecutorBenchmark.java

Add InfixOpNode and InfixOpOperators specific benchmarks
Fixes https://github.com/apache/incubator-kie-issues/issues/780
Continuation of https://github.com/apache/incubator-kie-benchmarks/pull/279 (closed due to branch renaming)

[incubator-kie-issues#780] DMN - Benchmarking InfixOpNode and InfixOperators

---

drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/operators/MatchesBenchmark.java

- Benchmark
With https://github.com/apache/incubator-kie-drools/pull/5837
Local results:
```
Benchmark              (_factsNumber)  (_rulesNumber)  (cacheEnabled)  Mode  Cnt  Score   Error  Units
MatchesBenchmark.test              32              16            true    ss   20  2.389 ± 0.278  ms/op
MatchesBenchmark.test              32              16           false    ss   20  2.157 ± 0.439  ms/op
MatchesBenchmark.test              32              32            true    ss   20  2.627 ± 0.517  ms/op
MatchesBenchmark.test              32              32           false    ss   20  3.466 ± 0.822  ms/op
MatchesBenchmark.test             256              16            true    ss   20  2.650 ± 0.521  ms/op
MatchesBenchmark.test             256              16           false    ss   20  4.716 …
```

[incubator-kie-drools-5841] Improve matches operator performance

---

.github/workflows/pull_request.yml

- https://github.com/apache/incubator-kie-benchmarks/issues/284
Now drools main is Java 17, so GHA Java 11 is not required. (Just fails now)

[incubator-kie-benchmarks-284] Remove GHA Java 11

---

.ci/jenkins/Jenkinsfile.bump-up-version

Part of:
* apache/incubator-kie-issues#776
Other related PRs:
* apache/incubator-kie-kogito-pipelines#1194
* apache/incubator-kie-benchmarks#286
* apache/incubator-kie-docs#4536
* apache/incubator-kie-kogito-runtimes#3501
* apache/incubator-kie-kogito-apps#2047
* apache/incubator-kie-kogito-examples#1914
* apache/incubator-kie-kogito-docs#626
* apache/incubator-kie-drools#5927
* apache/incubator-kie-optaplanner#3083
* apache/incubator-kie-kogito-serverless-operator#462
Replacing old approach to merge PRs:  merge locally + push into remote
New behavior relies on gh cli directly to approve and merge PR.

kie-issues#776: automate PR merge into protected branches

---

drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/feel/AbstractFEELBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/feel/EvaluationContextImplBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/feel/infixexecutors/FEELAddExecutorBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/feel/infixexecutors/FEELAndExecutorBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/feel/infixexecutors/FEELDivExecutorBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/feel/infixexecutors/FEELEqExecutorBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/feel/infixexecutors/FEELGtExecutorBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/feel/infixexecutors/FEELGteExecutorBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/feel/infixexecutors/FEELLtExecutorBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/feel/infixexecutors/FEELLteExecutorBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/feel/infixexecutors/FEELMultExecutorBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/feel/infixexecutors/FEELNeExecutorBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/feel/infixexecutors/FEELOrExecutorBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/feel/infixexecutors/FEELPowExecutorBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/feel/infixexecutors/FEELSubExecutorBenchmark.java

Fixes https://github.com/apache/incubator-kie-issues/issues/1300

[incubator-kie-issues#1300] Fix broken DMN benchmarks

---

drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/codegen/AbstractCodegenBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/codegen/CodegenBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/codegen/ImportedModelCodegenBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/codegen/PrequalificationCodegenBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/resources/dmn/Imported_Model_Unamed.dmn
drools-benchmarks-parent/drools-benchmarks/src/main/resources/dmn/Importing_EmptyNamed_Model_With_Href_Namespace.dmn
drools-benchmarks-parent/drools-benchmarks/src/main/resources/dmn/Prequalification.dmn

Fixes https://github.com/apache/incubator-kie-issues/issues/1301
This PR creates a couple of DMN benchmarks that
1. uses codegen for model instantiation
2. execute models for benchmarking

[incubator-kie-issues#1301] Create DMN benchmarks specifically targeting the codegen execution.

---

drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/ast/AbstractASTBenchmark.java
drools-benchmarks-parent/drools-benchmarks/src/main/java/org/drools/benchmarks/dmn/ast/ForExpressionNodeBenchmark.java

Related to 
https://github.com/apache/incubator-kie-issues/issues/1350
https://github.com/apache/incubator-kie-drools/pull/6041

[incubator-kie-issues#1350] Create AST benchmarks module to directly measure BaseNode's evaluation times. Implemented ForExpressionNodeBenchmark
